force-app/main/default/objects/Author__c/Author__c.object-meta.xml
<CustomObject>
    <description>Describes an Author</description>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Author__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipLabel>Authors</relationshipLabel>
    <relationshipName>Authors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BookController.cls
public class BookController 
{

    @AuraEnabled
    public static List<Book__c> getBooksByAuthor()
    {
        List<Book__c> bookByAuthor = new List<Book__c>();
 
        return bookByAuthor = [SELECT Name, Author__c FROM Book__c];
    }

    @AuraEnabled
    public static List<Book__c> getBooksByGenre()
    {
        List<Book__c> bookByGenre = new List<Book__c>();
        
        return bookByGenre = [SELECT Name, Genre__c FROM Book__c];
    }
}