force-app/main/default/objects/Publishing_House__c/Publishing_House__c.object-meta.xml
<CustomObject>
    <label>Publishing House</label>
    <nameField>
        <label>Publishing House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishing Houses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Publishing_House__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Publishing House Books</relationshipLabel>
    <relationshipName>Publishing_House_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PublishingHouseDomain.cls
public class PublishingHouseDomain 
 {
    public PublishingHouseDomain() 
    {
        
    }

    public static List<Book__c> getPublishedbooks(List<String> BookNameAndPublishingHouseName)
    {
        List<Publishing_House__c> publishingHouseBooks;
        List<Book__c> theBooks = new List<Book__c>();

        publishingHouseBooks = [SELECT Book__r FROM Publishing_House__c WHERE Book__r.name in: BookNameAndPublishingHouseName];

        for(Publishing_House__c phousebook: publishingHouseBooks)
        {
            theBooks.add(phousebook.Book__r);
        }
        
        return theBooks;
    }
}